name: "terraform-eks-dev"

on:
  push:
    branchs: ["develop"]
    paths: ["env/dev/**"]
  workflow_dispatch:

jobs: 
  desenvolvimento:
    name: "Network and EKS em DEV"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credencials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID_DEV }}