name: "destroy-desenvolvimento"

on:
  workflow_dispatch:

jobs: 
  desenvolvimento:
    name: "Destroy-Ambiente de Dev"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credencials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID_DEV }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Init
        working-directory: ./env/dev
        run: terraform init        

        - name: Terraform Destroy
        working-directory: ./env/dev
        run: terraform destroy --auto-approve